### ISSUE TITLE
[BUG] Login (and maybe other) requests do not properly throw / return errors

### ISSUE THREAD

**Issue by Foxhoundn** [qoretechnologies/qorus-toolkit#18]
**Describe the bug:**

When calling `QorusAuthenticator.initEndpoint(...)` with username and password, there is no return that indicates the call has failed other than some console reports.

**To Reproduce:**

Call `QorusAuthenticator.initEndpoint()` with some random data.

**Expected behavior:**

The method either needs to throw or the returned object needs to have an `error` key describing what happened.

**Screenshots or logs:**

```
await this.checkNoAuth();
      if (user && pass) await this.login({ user, pass });
      return this.selectedEndpoint;
``` 
**Desktop (please complete the following information):**

- OS: [e.g. Linux] MacOS
- Version [e.g. 22] Latest
- Library version [e.g. 1.0.0] 2.2.1 (should have been 0.2.2)

**Additional context**

This should have been caught by negative tests, so please make sure to add negative tests and add this logic to every method that  makes any kind of request.

**Comment by rishabhmalik759** [comment]
Added try catch and custom errors
