### ISSUE TITLE
[BUG] Do not save endpoint to the endpoints object if the check for `public` was not successful

### ISSUE THREAD

**Issue by Foxhoundn** [qoretechnologies/qorus-toolkit#21]
**Describe the bug:**

Do not save endpoint to the endpoints object if the check for `public` was not successful

**To Reproduce:**

`initEndpoint({ id: 'test', url: 'https://someurlthatdoesnotexist' })`

**Expected behavior:**

There should be no `test` endpoint existing if the call above fails and it should throw, right now there is.

**Comment by rishabhmalik759** [comment]
Fixed in previous commit
